### ISSUE TITLE
error npm run start-dev

### ISSUE THREAD

**Issue by anubislinux** [Palabola/Keira2Paladium#1]
D:\Desarrollo\Nueva carpeta\Keira2Paladium\app> npm run start-dev

> PaladiumEditor@0.0.0 start-dev D:\Desarrollo\Nueva carpeta\Keira2Paladium\app
> node app.js

D:\Desarrollo\Nueva carpeta\Keira2Paladium\app\node_modules\electron-settings\lib\settings.js:23
const app = electron.app || electron.remote.app;
                                            ^

TypeError: Cannot read property 'app' of undefined
    at Object.<anonymous> (D:\Desarrollo\Nueva carpeta\Keira2Paladium\app\node_modules\electron-settings\lib\settings.js:23:45)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Desarrollo\Nueva carpeta\Keira2Paladium\app\node_modules\electron-settings\index.js:17:18)
    at Module._compile (module.js:652:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! PaladiumEditor@0.0.0 start-dev: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the PaladiumEditor@0.0.0 start-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by anubislinux** [comment]
The steps I took were the following
1- npm install
2- npm install electron
3- npm run start-dev

but it does not work.
